version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cha-da-antonella-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cha_da_antonella
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 